### ISSUE TITLE
jsonErrors and Type Safety

### ISSUE THREAD

**Issue by StevenXL** [ocharles/digestive-functors-aeson#11]
Hello! 

First, thank you very much for this library. I'm incorporating it into my "how do I Servant" repo. (I'm very much a Haskell beginner).

Secondly, I noticed that if I have a value of type `View` that does not actually have any errors, and apply `jsonErrors` to that value, it will raise an exception. 

I was wondering if there is a minimially-intrusive way to increase the type safety of `jsonErrors`, and what I can do to help with that effort.

**Comment by ocharles** [comment]
Hi @StevenXL - sorry for never replying. If you're still curious about this, could you provide me with some example code that doesn't do what you'd like?
