### ISSUE TITLE
Optional primitives

### ISSUE THREAD

**Issue by prettynatty** [ocharles/digestive-functors-aeson#3]
`digestive-functors` is created for html forms there is no common way to define optional non-text form (or I can't find it?).
Is there any way to define, for example, `optionalBool`, `optionalInteger` in  `digestive-functors-aeson`? If no, consider it as feature request :)

**Comment by ocharles** [comment]
I am no longer adding features to this library, only maintaining it, sorry. If anyone submits a PR adding this feature, I will happily merge it.
