### ISSUE TITLE
Bump base to 4.8?

### ISSUE THREAD

**Issue by superduper** [ocharles/digestive-functors-aeson#5]
Hi! Have you tried digestive-functors-aeson with base-4.8.0? I wonder if it will work, there been a bit of changes https://hackage.haskell.org/package/base-4.8.0.0/changelog.

**Comment by ocharles** [comment]
It should work fine, I think I may even have a local copy with this bump. I'll try and get a new release out tomorrow.

**Comment by ocharles** [comment]
Fixed in 1.1.14.
